### PR TITLE
Release the retry if sigint/sigterm received

### PR DESCRIPTION
**Pull request by PuKoren**
@openrm/dev 

Previously the retry plugin was not releasing the backoff logic when a SIGINT/SIGTERM was received during the initial connection

### CODE REVIEW

**Comment by naggingant** [comment]
Thanks a lot!

This is my fault that I didn't add this mechanism already but I think the logic should be centralized somehow: the plugin system already has `destroy()` hook that is expected to be called on the client shutdown. Right now the graceful shutdown is a mere plugin but one way is to make this a builtin behaviour (i.e. essentially putting `process.on('SIGINT', () => client.close())` inside the core module) and there call the hook.
Please refer to [this plugin](https://github.com/openrm/hato/blob/master/plugins/conn-retry.js) and see how he releases his own resources.

**Comment by naggingant** [comment]
Oops sorry I misunderstood something, it IS the same plugin. Let me take a look why it didn't work as expected.

**Comment by naggingant** [comment]
@PuKoren re-posting a corrected comment:

The plugin already has `destroy()` hook implemented for the same reason, and it was expected to be triggered when the client is closed. But I think this was a unhandled case therefore the solution is to properly ensure that `destroy()` is called in the case.

I pushed a change in attempt to achieve this here: https://github.com/openrm/hato/compare/fix/destroy-hook
Could you try it out to see if it fixes the issue?

**Comment by PuKoren** [comment]
@naggingant unfortunately it does not fix the issue for me
the promise chain is locked at the channel close until the retry plugin releases

**Comment by naggingant** [comment]
Okay, got it.
Could you explain how to reproduce it? I would like to try to find a way myself.

Even if this was the only way,  we should make the driver call `destroy()` I think :thinking:

**Comment by PuKoren** [comment]
To reproduce it you can start a service without rabbitmq running, so it will trigger the retry logic
Then if you try to interrupt the program, you will have to wait until the retry plugin gives up to see the service shutting down

its minor issue, as in the worst case user will have to wait the specified timeout to have the node program gracefully shutdown

**Comment by PuKoren** [comment]
I'll let you merge it when you want as you are leading on hato :bow:

**Comment by naggingant** [comment]
Got it, thanks a lot for working on this!

**Pull request merged**
